---
- name: Install pip packages for app
  pip:
    name:
      - gunicorn
      - flask
      - psycopg2-binary

- name: Clone application code
  git:
    repo: "{{ app_repo_url }}"
    dest: "{{ app_dir }}"
    version: main

- name: Write Gunicorn systemd service
  template:
    src: gunicorn.service.j2
    dest: "/etc/systemd/system/{{ app_service }}.service"
  notify: restart app

- name: Start and enable app service
  systemd:
    name: "{{ app_service }}"
    state: started
    enabled: yes
